/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.techscode.com/repository/techscode-apis/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/nms/")
    }

    maven {
        url = uri("https://repo.repsy.io/mvn/kiran/tweetzy")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.aikar.co/content/groups/aikar/")
    }

    maven {
        url = uri("https://mvn.lumine.io/repository/maven-public/")
    }

    maven {
        url = uri("https://nexus.neetgames.com/repository/maven-releases/")
    }

    maven {
        url = uri("https://repo.opencollab.dev/maven-snapshots/")
    }

    maven {
        url = uri("https://bitbucket.org/kangarko/libraries/raw/master")
    }

    maven {
        url = uri("https://repo.essentialsx.net/releases/")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://m2.dv8tion.net/releases")
    }

    maven {
        url = uri("https://nexus.scarsz.me/content/groups/public/")
    }

    maven {
        url = uri("https://repo.minebench.de/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.auxilor.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.rosewooddev.io/repository/public/")
    }

    maven {
        url = uri("https://repo.nightexpressdev.com/releases")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://nexus.hartserver.ca/repository/maven-releases")
    }
}

dependencies {
    api(libs.ca.tweetzy.flight)
    api(libs.ca.tweetzy.tweetycore)
    api(libs.ca.tweetzy.funds)
    api(libs.su.nightexpress.coinsengine.coinsengine) {
        isTransitive = false
    }
    api(libs.com.github.zrips.cmi.api)
    api(libs.co.aikar.taskchain.bukkit)
    api(libs.com.zaxxer.hikaricp)
    api(libs.io.lumine.mythiclib)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.slf4j.slf4j.nop)
    api(libs.com.google.code.gson.gson)
    compileOnly(libs.org.spigotmc.spigot)
    compileOnly(libs.com.github.milkbowl.vaultapi)
    compileOnly(libs.com.willfp.ecobits)
    compileOnly(libs.com.willfp.ecoitems)
    compileOnly(libs.org.black.ixx.playerpoints)
    compileOnly(libs.net.essentialsx.essentialsx)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(libs.me.clip.placeholderapi)
    compileOnly(libs.me.techscode.ultraeconomyapi)
    compileOnly(libs.com.acrobot.chestshop.chestshop)
    compileOnly(libs.org.geysermc.floodgate.api)
}

group = "ca.tweetzy"
version = "2.155.1"
description = "AuctionHouse"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
